
import React, { useLayoutEffect, useRef, useState, useEffect } from 'react';
import { useAppContext } from '../contexts/AppContext';

// GSAP declarations for CDN usage
declare var gsap: any;
declare var ScrollTrigger: any;
declare const Prism: any; // Ensure Prism is accessible

interface LandingPageProps {
  onStart: () => void;
}

const CODE_SNIPPET = `import React from 'react';
import { motion } from 'framer-motion';

// AI Generated Component
export const FutureUI = () => {
  return (
    <motion.div
      initial={{ y: 20, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      className="p-6 bg-white rounded-2xl shadow-xl"
    >
      <h1 className="text-3xl font-bold text-gray-900">
        Hello World
      </h1>
      <p className="text-gray-500 mt-2">
        Generated by Gemini 2.0
      </p>
    </motion.div>
  );
}`;

const LandingPage: React.FC<LandingPageProps> = ({ onStart }) => {
  const { t } = useAppContext();
  const containerRef = useRef<HTMLDivElement>(null);
  
  // 3D Tilt State
  const [tilt, setTilt] = useState({ x: 0, y: 0 });
  const [mouseFactor, setMouseFactor] = useState({ x: 0, y: 0 }); // Normalized -1 to 1
  const [isHovering, setIsHovering] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  // Typing Effect State
  const [typedCode, setTypedCode] = useState('');
  const [showCursor, setShowCursor] = useState(true);
  const [hasStartedTyping, setHasStartedTyping] = useState(false);

  // Mouse Glow State
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });

  // Handle 3D Tilt on Hero Card
  const handleHeroMouseEnter = () => {
    setIsHovering(true);
  };

  const handleHeroMouseMove = (e: React.MouseEvent) => {
    if (!cardRef.current) return;
    const rect = cardRef.current.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    
    // Normalized coordinates (-1 to 1)
    const normX = (x / rect.width) * 2 - 1;
    const normY = (y / rect.height) * 2 - 1;
    
    setMouseFactor({ x: normX, y: normY });

    // Calculate rotation (Max 15deg)
    const xRot = normY * -15;
    const yRot = normX * 15;

    setTilt({ x: xRot, y: yRot });
  };

  const handleHeroMouseLeave = () => {
    setIsHovering(false);
    setTilt({ x: 0, y: 0 });
    setMouseFactor({ x: 0, y: 0 });
  };

  // Handle Global Mouse Move for Glow Effect
  useEffect(() => {
    const handleWindowMouseMove = (e: MouseEvent) => {
        setMousePos({ x: e.clientX, y: e.clientY });
    };
    window.addEventListener('mousemove', handleWindowMouseMove);
    return () => window.removeEventListener('mousemove', handleWindowMouseMove);
  }, []);

  // Typing Effect Logic
  useEffect(() => {
    // Only start typing once animation might have brought it into view roughly
    const startDelay = setTimeout(() => {
        setHasStartedTyping(true);
    }, 1500);

    return () => clearTimeout(startDelay);
  }, []);

  useEffect(() => {
    if (!hasStartedTyping) return;

    let currentIndex = 0;
    const typeInterval = setInterval(() => {
        if (currentIndex < CODE_SNIPPET.length) {
            setTypedCode(CODE_SNIPPET.slice(0, currentIndex + 1));
            currentIndex++;
        } else {
            clearInterval(typeInterval);
        }
    }, 30); // Typing speed ms

    return () => clearInterval(typeInterval);
  }, [hasStartedTyping]);

  // Blinking Cursor
  useEffect(() => {
      const blinkInterval = setInterval(() => {
          setShowCursor(prev => !prev);
      }, 500);
      return () => clearInterval(blinkInterval);
  }, []);

  // Safe Prism Highlight
  const getHighlightedHtml = () => {
      if (typeof Prism !== 'undefined' && Prism.languages && Prism.languages.tsx) {
          return Prism.highlight(typedCode, Prism.languages.tsx, 'tsx');
      }
      // Fallback simple highlighting if Prism isn't ready
      return typedCode
        .replace(/import|from|return|export|const/g, '<span class="text-purple-400">$&</span>')
        .replace(/'[^']*'/g, '<span class="text-green-400">$&</span>')
        .replace(/\/\/.*$/gm, '<span class="text-slate-500 italic">$&</span>');
  };

  useLayoutEffect(() => {
    if (typeof gsap !== 'undefined' && typeof ScrollTrigger !== 'undefined' && containerRef.current) {
        gsap.registerPlugin(ScrollTrigger);
        
        const scroller = containerRef.current;
        const ctx = gsap.context(() => {
            
            // 1. Initial Hero Entry (Time-based, no scroll)
            const tl = gsap.timeline({ defaults: { ease: "power3.out" } });
            
            tl.fromTo(".hero-text-item", 
                { y: 40, opacity: 0 },
                { y: 0, opacity: 1, duration: 1, stagger: 0.15 }
            )
            .fromTo(".hero-card-wrapper",
                { y: 60, opacity: 0, rotateX: 10 },
                { y: 0, opacity: 1, rotateX: 0, duration: 1.2, ease: "back.out(1.5)" },
                "-=0.8"
            );

            // 2. Scroll Triggered Animations for Features
            const cards = gsap.utils.toArray(".feature-card");
            if (cards.length > 0) {
                 gsap.fromTo(cards, 
                    { y: 60, opacity: 0 },
                    {
                        y: 0,
                        opacity: 1,
                        duration: 0.8,
                        stagger: 0.1,
                        ease: "power2.out",
                        scrollTrigger: {
                            trigger: "#features",
                            scroller: scroller,
                            start: "top 85%", // Triggers earlier to ensure visibility on jump
                            toggleActions: "play none none none" // Persist: Don't hide when scrolling back
                        }
                    }
                );
            }

            // 3. Workflow Steps
            const steps = gsap.utils.toArray(".workflow-step");
            steps.forEach((step: any, i: number) => {
                const direction = i % 2 === 0 ? -50 : 50;
                gsap.fromTo(step,
                    { x: direction, opacity: 0 },
                    {
                        x: 0, 
                        opacity: 1,
                        duration: 1,
                        ease: "power3.out",
                        scrollTrigger: {
                            trigger: step,
                            scroller: scroller,
                            start: "top 85%",
                            toggleActions: "play none none none" 
                        }
                    }
                );
            });

             // 4. Parallax Background Bubbles
             gsap.to(".bg-blob-1", {
                 y: 200,
                 scrollTrigger: {
                     trigger: ".parallax-trigger",
                     scroller: scroller,
                     start: "top top",
                     end: "bottom bottom",
                     scrub: 2
                 }
             });
             gsap.to(".bg-blob-2", {
                 y: -150,
                 scrollTrigger: {
                     trigger: ".parallax-trigger",
                     scroller: scroller,
                     start: "top top",
                     end: "bottom bottom",
                     scrub: 3
                 }
             });

        }, containerRef);

        return () => ctx.revert();
    }
  }, []);

  return (
    <div 
        ref={containerRef} 
        className="landing-container w-full h-full overflow-y-auto bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 transition-colors duration-200 font-sans custom-scrollbar scroll-smooth relative snap-y snap-proximity scroll-pt-16"
    >
      
      {/* Background Ambience & Parallax Elements */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden parallax-trigger">
          <div className="bg-blob-1 absolute top-[-10%] left-[-10%] w-[600px] h-[600px] bg-brand-500/10 dark:bg-brand-500/5 rounded-full blur-[100px] animate-blob"></div>
          <div className="bg-blob-2 absolute top-[30%] right-[-10%] w-[500px] h-[500px] bg-purple-500/10 dark:bg-purple-500/5 rounded-full blur-[100px] animate-blob animation-delay-2000"></div>
          <div className="bg-blob-3 absolute bottom-[-10%] left-[20%] w-[700px] h-[700px] bg-blue-500/10 dark:bg-blue-500/5 rounded-full blur-[100px] animate-blob animation-delay-4000"></div>
          
          {/* Noise & Grid Overlay */}
          <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 dark:opacity-5 mix-blend-overlay"></div>
          <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:40px_40px]"></div>
      </div>

      {/* Hero Section */}
      <section className="snap-start relative min-h-[90vh] flex items-center justify-center pt-24 pb-20 px-6 overflow-hidden">
        <div className="max-w-7xl w-full mx-auto flex flex-col lg:flex-row items-center gap-16 lg:gap-8">
            
            {/* Left: Text Content */}
            <div className="lg:w-1/2 text-left z-10 space-y-8">
                <div className="hero-text-item inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-brand-50 dark:bg-brand-900/20 text-brand-700 dark:text-brand-300 text-xs font-bold uppercase tracking-widest border border-brand-200 dark:border-brand-800 shadow-sm backdrop-blur-sm">
                   <span className="relative flex h-2 w-2">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-400 opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-2 w-2 bg-brand-500"></span>
                    </span>
                   {t('landing_hero_tag')}
                </div>
                
                <h1 className="hero-text-item text-5xl sm:text-6xl md:text-7xl font-extrabold tracking-tight leading-[1.1]">
                   {t('landing_hero_title_1')} <br/>
                   <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-600 via-purple-600 to-brand-600 dark:from-brand-400 dark:via-purple-400 dark:to-brand-400 bg-300% animate-gradient">
                     {t('landing_hero_title_2')}
                   </span>
                </h1>
                
                <p className="hero-text-item text-lg sm:text-xl text-slate-600 dark:text-slate-400 leading-relaxed max-w-lg">
                   {t('landing_hero_desc')}
                </p>
                
                <div className="hero-text-item flex flex-wrap gap-4">
                   <button 
                     onClick={onStart}
                     className="group relative px-8 py-4 bg-slate-900 dark:bg-white text-white dark:text-slate-900 text-lg font-bold rounded-xl shadow-2xl hover:shadow-brand-500/25 overflow-hidden transition-all duration-300 hover:-translate-y-1"
                   >
                      <div className="absolute inset-0 w-full h-full bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:animate-shimmer"></div>
                      <span className="relative flex items-center gap-2">
                        {t('landing_cta_start')}
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 transition-transform group-hover:translate-x-1" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" />
                        </svg>
                      </span>
                   </button>
                   
                   <button 
                     onClick={() => document.getElementById('features')?.scrollIntoView({behavior: 'smooth'})}
                     className="px-8 py-4 bg-white/50 dark:bg-slate-800/50 backdrop-blur border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-white text-lg font-semibold rounded-xl hover:bg-white dark:hover:bg-slate-800 transition-all duration-300 hover:scale-105"
                   >
                      {t('landing_cta_explore')}
                   </button>
                </div>

                <div className="hero-text-item flex items-center gap-4 text-sm text-slate-500 dark:text-slate-400 font-medium">
                    <div className="flex -space-x-2">
                        {[1,2,3].map(i => (
                            <div key={i} className="w-8 h-8 rounded-full border-2 border-white dark:border-slate-950 bg-slate-200 dark:bg-slate-700 flex items-center justify-center text-xs overflow-hidden">
                                <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${i}`} alt="user" />
                            </div>
                        ))}
                    </div>
                    <span>Trusted by 1,000+ developers</span>
                </div>
            </div>

            {/* Right: Interactive 3D Card */}
            <div 
                className="lg:w-1/2 relative z-10 hero-card-wrapper perspective-1000 flex justify-center lg:justify-end"
                onMouseEnter={handleHeroMouseEnter}
                onMouseMove={handleHeroMouseMove}
                onMouseLeave={handleHeroMouseLeave}
            >
                <div 
                    ref={cardRef}
                    className="relative w-full max-w-lg ease-out transform-style-3d cursor-pointer"
                    style={{ 
                        transform: `rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)`,
                        // Dynamic transition: fast when hovering (responsive), slow when leaving (smooth reset)
                        transition: isHovering ? 'transform 0.1s ease-out' : 'transform 0.6s ease-[cubic-bezier(0.23,1,0.32,1)]'
                    }}
                >
                    {/* Decorative Elements sticking out in 3D (Parallax) 
                        WE USE NEGATIVE TRANSLATION FACTOR for foreground elements to exaggerate parallax 
                        when the card rotates away.
                    */}
                    
                    {/* Top Right Box - Pops out (Positive Z) - Added explicit translation for "looseness" */}
                    <div 
                        className="absolute -top-12 -right-12 w-28 h-28 bg-gradient-to-br from-yellow-400 to-orange-500 rounded-2xl z-20 shadow-lg animate-float pointer-events-none"
                        style={{ 
                            transform: `translateZ(80px) translateX(${mouseFactor.x * -20}px) translateY(${mouseFactor.y * -20}px)`,
                            transition: isHovering ? 'transform 0.1s ease-out' : 'transform 0.6s ease-out'
                        }}
                    ></div>
                    
                    {/* Bottom Left Blob - Sits behind (Negative Z) - Moves in opposition to front */}
                    <div 
                        className="absolute -bottom-12 -left-12 w-40 h-40 bg-gradient-to-tr from-brand-400 to-cyan-500 rounded-full z-0 blur-xl opacity-60 animate-pulse-slow pointer-events-none"
                        style={{ 
                            transform: `translateZ(-80px) translateX(${mouseFactor.x * 20}px) translateY(${mouseFactor.y * 20}px)`,
                            transition: isHovering ? 'transform 0.1s ease-out' : 'transform 0.6s ease-out'
                        }}
                    ></div>
                    
                    {/* The Code Window */}
                    <div 
                        className="bg-slate-900/95 dark:bg-slate-900/95 rounded-2xl shadow-2xl overflow-hidden border border-slate-700/50 backdrop-blur-xl relative z-10 transform ring-1 ring-white/10"
                        style={{ transform: 'translateZ(0px)' }}
                    >
                        {/* Fake Mac Header */}
                        <div className="flex items-center justify-between px-4 py-3 border-b border-slate-800 bg-slate-800/50">
                            <div className="flex gap-2">
                                <div className="w-3 h-3 rounded-full bg-[#ff5f56]"></div>
                                <div className="w-3 h-3 rounded-full bg-[#ffbd2e]"></div>
                                <div className="w-3 h-3 rounded-full bg-[#27c93f]"></div>
                            </div>
                            <div className="text-xs text-slate-400 font-mono flex items-center gap-2 opacity-70">
                                LandingPage.tsx
                            </div>
                            <div className="w-10"></div>
                        </div>
                        
                        {/* Code Content with Typing Effect */}
                        <div className="p-6 overflow-x-auto relative group h-[340px] custom-scrollbar">
                            {/* Hover effect for code */}
                            <div className="absolute inset-0 bg-gradient-to-b from-transparent to-slate-900/50 pointer-events-none"></div>
                            
                            <pre className="text-sm font-mono leading-relaxed relative z-10 text-slate-300">
                              <code dangerouslySetInnerHTML={{ __html: getHighlightedHtml() }} />
                              <span className={`${showCursor ? 'opacity-100' : 'opacity-0'} text-brand-400 font-bold ml-0.5`}>|</span>
                           </pre>
                        </div>
                    </div>

                    {/* Reflection/Shine Effect */}
                    <div 
                        className="absolute inset-0 rounded-2xl pointer-events-none z-30 opacity-20 mix-blend-overlay transition-opacity duration-300"
                        style={{
                            background: `linear-gradient(120deg, transparent 40%, white 50%, transparent 60%)`,
                            backgroundSize: '200% 100%',
                            backgroundPosition: `${50 + (tilt.y * 2.5)}% center`,
                            transform: 'translateZ(1px)' // Sits slightly above card
                        }}
                    ></div>
                </div>
            </div>
        </div>
      </section>

      {/* Features Bento Grid */}
      <section id="features" className="snap-start py-24 px-6 relative z-10 bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm border-t border-slate-200 dark:border-slate-800">
         <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
                <span className="text-brand-600 dark:text-brand-400 font-bold tracking-wider uppercase text-sm mb-2 block">{t('features_title')}</span>
                <h2 className="text-3xl md:text-5xl font-bold mb-4 text-slate-900 dark:text-white">{t('features_subtitle')}</h2>
            </div>

            <div 
                className="grid grid-cols-1 md:grid-cols-3 gap-6 auto-rows-[minmax(300px,auto)]"
                onMouseMove={(e) => {
                    const cards = document.querySelectorAll('.feature-card');
                    cards.forEach(card => {
                        const rect = card.getBoundingClientRect();
                        const x = e.clientX - rect.left;
                        const y = e.clientY - rect.top;
                        (card as HTMLElement).style.setProperty('--mouse-x', `${x}px`);
                        (card as HTMLElement).style.setProperty('--mouse-y', `${y}px`);
                    });
                }}
            >
                {/* Feature 1: Universal AI Models (Span 2) */}
                <div className="feature-card md:col-span-2 bg-gradient-to-br from-slate-900 to-slate-800 border border-slate-700 rounded-3xl p-8 text-white relative overflow-hidden group hover:shadow-2xl hover:shadow-brand-500/10 transition-all duration-300">
                     <div className="relative z-10 h-full flex flex-col justify-between">
                         <div>
                             <div className="flex items-center gap-2 mb-3">
                                <span className="px-2 py-1 rounded bg-brand-500/20 text-brand-300 text-[10px] font-bold uppercase tracking-wider border border-brand-500/30">New</span>
                                <h3 className="text-2xl font-bold">{t('feature_universal_title')}</h3>
                             </div>
                             <p className="text-slate-400 max-w-sm leading-relaxed">{t('feature_universal_desc')}</p>
                         </div>
                         <div className="flex flex-wrap gap-3 mt-8">
                             {[
                                { name: 'Gemini 2.0', color: 'bg-blue-500/20 text-blue-300 border-blue-500/30' },
                                { name: 'GPT-4o', color: 'bg-green-500/20 text-green-300 border-green-500/30' },
                                { name: 'DeepSeek', color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30' },
                                { name: 'Groq', color: 'bg-orange-500/20 text-orange-300 border-orange-500/30' }
                             ].map((model) => (
                                 <span key={model.name} className={`px-3 py-1.5 backdrop-blur-md rounded-lg text-sm font-medium border ${model.color} transition-transform hover:scale-105 cursor-default`}>
                                     {model.name}
                                 </span>
                             ))}
                         </div>
                     </div>
                     <div className="absolute right-0 top-0 w-64 h-64 bg-brand-500/10 rounded-full blur-[80px] pointer-events-none"></div>
                </div>

                {/* Feature 2: Visual Editor (Span 1) */}
                <div className="feature-card bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-3xl p-8 relative overflow-hidden group hover:border-brand-500/50 transition-all duration-300">
                     {/* Glow Overlay */}
                     <div 
                        className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"
                        style={{
                            background: `radial-gradient(600px circle at var(--mouse-x) var(--mouse-y), rgba(59, 130, 246, 0.1), transparent 40%)`
                        }}
                     ></div>

                     <div className="absolute top-4 right-4 w-12 h-12 bg-green-100 dark:bg-green-900/30 rounded-xl flex items-center justify-center text-green-600 group-hover:scale-110 transition-transform duration-300">
                        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"/></svg>
                     </div>
                     <h3 className="text-xl font-bold mb-2 text-slate-900 dark:text-white relative z-10">{t('feature_visual_title')}</h3>
                     <p className="text-sm text-slate-500 dark:text-slate-400 mb-6 relative z-10">{t('feature_visual_desc')}</p>
                     <div className="absolute bottom-4 left-4 right-4 bg-slate-100 dark:bg-slate-900 rounded-lg p-3 border border-slate-200 dark:border-slate-700 shadow-sm group-hover:translate-y-[-5px] transition-transform duration-300">
                         <div className="text-xs text-brand-600 mb-1 font-semibold flex items-center gap-1">
                             <span className="w-2 h-2 rounded-full bg-brand-500 animate-pulse"></span>
                             {t('feature_visual_prompt_label')}
                         </div>
                         <div className="text-xs text-slate-500 italic">"{t('feature_visual_prompt_text')}"</div>
                     </div>
                </div>

                {/* Feature 3: Reverse Engineering (Span 1) - Updated Visuals */}
                <div className="feature-card bg-slate-900 border border-slate-800 rounded-3xl p-8 relative overflow-hidden group hover:border-purple-500/50 transition-all duration-500">
                    {/* Background Glow */}
                    <div className="absolute top-0 right-0 w-[300px] h-[300px] bg-purple-500/20 blur-[100px] rounded-full translate-x-1/2 -translate-y-1/2 group-hover:bg-purple-500/30 transition-colors duration-500"></div>
                    
                    <div className="relative z-10 flex flex-col h-full">
                        {/* Header */}
                        <div className="mb-auto">
                            <div className="w-12 h-12 bg-purple-500/20 rounded-xl flex items-center justify-center text-purple-400 mb-4 group-hover:scale-110 transition-transform duration-300 border border-purple-500/30">
                                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" /></svg>
                            </div>
                            <h3 className="text-xl font-bold mb-2 text-white">{t('feature_reverse_title')}</h3>
                            <p className="text-sm text-slate-400">{t('feature_reverse_desc')}</p>
                        </div>

                        {/* Visual Visualization */}
                        <div className="h-32 relative mt-6 flex items-center justify-center">
                            {/* Code File (Left) */}
                            <div className="absolute left-4 top-1/2 -translate-y-1/2 w-20 h-28 bg-slate-800 border border-slate-700 rounded-lg p-2 transform -rotate-6 group-hover:-rotate-12 group-hover:-translate-x-2 transition-all duration-500 shadow-xl z-10">
                                <div className="flex gap-1 mb-2"><div className="w-1.5 h-1.5 rounded-full bg-red-500/80"></div><div className="w-1.5 h-1.5 rounded-full bg-yellow-500/80"></div></div>
                                <div className="space-y-1.5">
                                    <div className="h-1 w-full bg-slate-600 rounded opacity-50"></div>
                                    <div className="h-1 w-3/4 bg-blue-500/50 rounded"></div>
                                    <div className="h-1 w-1/2 bg-purple-500/50 rounded"></div>
                                    <div className="h-1 w-full bg-slate-600 rounded opacity-30"></div>
                                    <div className="h-1 w-2/3 bg-slate-600 rounded opacity-30"></div>
                                </div>
                            </div>

                            {/* Arrow/Process */}
                            <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 z-20 text-purple-500 opacity-50 group-hover:opacity-100 group-hover:scale-125 transition-all duration-300">
                                <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                                </svg>
                            </div>

                            {/* Doc File (Right) */}
                            <div className="absolute right-4 top-1/2 -translate-y-1/2 w-20 h-28 bg-white border border-slate-200 rounded-lg p-2 transform rotate-6 group-hover:rotate-12 group-hover:translate-x-2 transition-all duration-500 shadow-xl z-10">
                                <div className="w-6 h-6 bg-slate-100 rounded mb-2 flex items-center justify-center text-[8px] font-bold text-slate-400">MD</div>
                                <div className="space-y-1.5">
                                    <div className="h-1.5 w-full bg-slate-800 rounded"></div>
                                    <div className="h-1 w-full bg-slate-300 rounded"></div>
                                    <div className="h-1 w-5/6 bg-slate-300 rounded"></div>
                                    <div className="h-1 w-4/6 bg-slate-300 rounded"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                 {/* Feature 4: Global Settings (Span 2) - New */}
                 <div className="feature-card md:col-span-2 bg-gradient-to-br from-indigo-600 to-blue-700 rounded-3xl p-8 text-white relative overflow-hidden border border-indigo-500/50 group">
                     <div className="relative z-10 flex flex-col md:flex-row items-center gap-8 h-full">
                         <div className="flex-1">
                             <h3 className="text-2xl font-bold mb-2">{t('feature_settings_title')}</h3>
                             <p className="text-indigo-100 mb-6">{t('feature_settings_desc')}</p>
                             <div className="flex gap-2">
                                <span className="px-3 py-1 bg-white/10 rounded-full text-xs border border-white/20">System Prompts</span>
                                <span className="px-3 py-1 bg-white/10 rounded-full text-xs border border-white/20">API Keys</span>
                                <span className="px-3 py-1 bg-white/10 rounded-full text-xs border border-white/20">Presets</span>
                             </div>
                         </div>
                         <div className="flex-1 w-full max-w-sm relative">
                             {/* Abstract UI representation of settings */}
                             <div className="bg-white/10 backdrop-blur-md rounded-lg p-4 border border-white/20 transform rotate-1 group-hover:rotate-0 transition-transform duration-500 hover:scale-105">
                                 <div className="space-y-3">
                                     <div className="flex items-center justify-between">
                                         <div className="w-1/3 h-2 bg-white/30 rounded"></div>
                                         <div className="w-8 h-4 bg-brand-400 rounded-full"></div>
                                     </div>
                                     <div className="w-full h-1 bg-white/20 rounded-full overflow-hidden">
                                         <div className="w-2/3 h-full bg-brand-400"></div>
                                     </div>
                                      <div className="flex items-center gap-2">
                                         <div className="w-8 h-8 rounded bg-white/20"></div>
                                         <div className="w-1/2 h-2 bg-white/30 rounded"></div>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
            </div>
         </div>
      </section>

      {/* Workflow Section */}
      <section id="workflow" className="snap-start py-24 px-6 relative z-10">
          <div className="max-w-4xl mx-auto">
              <div className="text-center mb-16">
                  <span className="text-brand-600 dark:text-brand-400 font-bold tracking-wider uppercase text-sm bg-brand-50 dark:bg-brand-900/20 px-3 py-1 rounded-full">{t('workflow_label')}</span>
                  <h2 className="text-3xl md:text-5xl font-bold mt-4 text-slate-900 dark:text-white">{t('workflow_title')}</h2>
              </div>

              <div className="space-y-12 relative">
                  {/* Connector Line */}
                  <div className="absolute left-8 md:left-1/2 top-0 bottom-0 w-0.5 bg-gradient-to-b from-slate-200 via-brand-200 to-slate-200 dark:from-slate-800 dark:via-brand-900 dark:to-slate-800 -translate-x-1/2 hidden md:block"></div>

                  {[
                      { title: t('workflow_step1_title'), desc: t('workflow_step1_desc'), icon: "1" },
                      { title: t('workflow_step2_title'), desc: t('workflow_step2_desc'), icon: "2" },
                      { title: t('workflow_step3_title'), desc: t('workflow_step3_desc'), icon: "3" },
                      { title: t('workflow_step4_title'), desc: t('workflow_step4_desc'), icon: "4" }
                  ].map((step, i) => (
                      <div key={i} className={`workflow-step flex flex-col md:flex-row items-center gap-8 ${i % 2 !== 0 ? 'md:flex-row-reverse' : ''} group`}>
                          <div className={`flex-1 md:text-right ${i % 2 !== 0 ? 'md:text-left' : ''}`}>
                              {i % 2 === 0 && (
                                  <>
                                     <h3 className="text-xl font-bold text-slate-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors">{step.title}</h3>
                                     <p className="text-slate-500 dark:text-slate-400 mt-2">{step.desc}</p>
                                  </>
                              )}
                          </div>
                          
                          <div className="relative z-10">
                             <div className="w-16 h-16 rounded-full bg-white dark:bg-slate-800 border-4 border-slate-100 dark:border-slate-700 group-hover:border-brand-500 group-hover:scale-110 transition-all duration-300 flex items-center justify-center shadow-xl text-xl font-bold text-slate-400 group-hover:text-brand-600">
                                 {step.icon}
                             </div>
                          </div>

                          <div className={`flex-1 ${i % 2 === 0 ? 'md:text-left' : 'md:text-right'}`}>
                              {i % 2 !== 0 && (
                                  <>
                                     <h3 className="text-xl font-bold text-slate-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors">{step.title}</h3>
                                     <p className="text-slate-500 dark:text-slate-400 mt-2">{step.desc}</p>
                                  </>
                              )}
                          </div>
                      </div>
                  ))}
              </div>
          </div>
      </section>

      {/* CTA Footer - Redesigned to match glassmorphism aesthetics */}
      <section id="cta-section" className="snap-start py-24 px-6 relative overflow-hidden bg-brand-50 dark:bg-slate-900 border-t border-brand-100 dark:border-slate-800">
          <div className="absolute inset-0 pointer-events-none">
             {/* Subtle animated gradient background for light/dark consistency */}
             <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-b from-transparent to-white/50 dark:to-black/20"></div>
             <div className="absolute -top-[50%] -left-[20%] w-[100%] h-[100%] bg-brand-400/10 blur-[100px] rounded-full animate-blob"></div>
             <div className="absolute top-[20%] -right-[20%] w-[80%] h-[80%] bg-purple-400/10 blur-[100px] rounded-full animate-blob animation-delay-2000"></div>
          </div>

          <div className="max-w-4xl mx-auto text-center relative z-10">
              <h2 className="text-4xl md:text-6xl font-bold mb-8 tracking-tight text-slate-900 dark:text-white">{t('ready_title')}</h2>
              <p className="text-xl text-slate-600 dark:text-slate-300 mb-10 max-w-2xl mx-auto">{t('ready_desc')}</p>
              <button 
                onClick={onStart}
                className="group px-10 py-5 bg-gradient-to-r from-brand-600 to-indigo-600 hover:from-brand-500 hover:to-indigo-500 text-white text-lg font-bold rounded-full shadow-lg hover:shadow-brand-500/30 hover:-translate-y-1 transition-all duration-300 flex items-center gap-2 mx-auto"
              >
                  {t('launch_editor')}
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 group-hover:translate-x-1 transition-transform" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd" />
                  </svg>
              </button>
          </div>
      </section>

      {/* Simple Footer */}
      <footer className="snap-start py-8 bg-slate-100 dark:bg-slate-950 text-slate-500 text-center text-sm border-t border-slate-200 dark:border-slate-900">
          <p>© {new Date().getFullYear()} MarkWeb. {t('footer_copyright')}</p>
      </footer>

    </div>
  );
};

export default LandingPage;
